# Generated by Django 4.2 on 2023-04-13 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Coin Symbol')),
                ('coin_id', models.CharField(max_length=50, verbose_name='Coin ID for API')),
                ('entry_price', models.DecimalField(blank=True, decimal_places=10, max_digits=15)),
                ('entry_amount', models.DecimalField(decimal_places=10, max_digits=15)),
                ('entry_date', models.DateField(auto_now_add=True, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('exit_date', models.DateField(auto_now=True, null=True)),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
